version: '3'
services:
  file-generator:
    image: mbtiles_converter:latest  # Replace with your actual image name and tag
    volumes:
      - ./output:/app/output  # Mount a host directory to store generated files
    ports:
      - "3000:3000"  # Map container port 3000 to host port 3000
    build:
      context: .  # Use the current directory as build context
      dockerfile: Dockerfile  # Use the Dockerfile in the current directory

  file-server:
    image: nginx:latest  # Using NGINX as a simple file server
    ports:
      - "8000:8000"  # Expose NGINX on host port 8000
    volumes:
      - ./output:/usr/share/nginx/html  # Serve files from the output directory of file-generator
